package database;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * NotepadWriter handles writing account information to a text file.
 * Creates a standard .txt file that can be opened in Windows Notepad.
 */
public class NotepadWriter {
    
    private static final String NOTEPAD_FILE = "accounts.txt";
    
    /**
     * Writes account information to a notepad-compatible text file
     * @param users List of UserData objects to write
     */
    public void writeAccountsToFile(List<UserData> users) {
        try (FileWriter writer = new FileWriter(NOTEPAD_FILE, StandardCharsets.UTF_8)) {
            // ============================================================================
            // FILE PURPOSE AND INFORMATION
            // ============================================================================
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("                    ACCOUNT LIST - WellCo System\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("\n");
            writer.write("PURPOSE:\n");
            writer.write("--------\n");
            writer.write("This file stores all user account information for the WellCo application.\n");
            writer.write("It serves as a backup and synchronization point between SQL database and\n");
            writer.write("in-memory (ArrayList) storage. The file is automatically updated whenever\n");
            writer.write("accounts are created, modified, or deleted through the application.\n");
            writer.write("\n");
            writer.write("FILE FORMAT:\n");
            writer.write("-----------\n");
            writer.write("The file uses a pipe-separated (|) format for readability in Notepad.\n");
            writer.write("Each account line contains the following fields in order:\n");
            writer.write("  1. ROLE           - User role (Customer, Manager, or Admin)\n");
            writer.write("  2. USERNAME       - Unique username for login\n");
            writer.write("  3. PASSWORD       - User password (stored in plain text for backup)\n");
            writer.write("  4. EMAIL          - User email address\n");
            writer.write("  5. CREATED DATE    - Account creation timestamp (yyyy-MM-dd HH:mm:ss)\n");
            writer.write("  6. ORIGINAL USERNAME - Original username (for account history)\n");
            writer.write("\n");
            writer.write("ALTERNATIVE FORMAT (for manual editing):\n");
            writer.write("---------------------------------------\n");
            writer.write("You can also use comma-separated format when manually editing:\n");
            writer.write("  ROLE, USERNAME, Password, Email, CreatedDate, OriginalUsername\n");
            writer.write("Example: Customer, john_doe, password123, john@email.com, 2025-01-15 10:30:00, john_doe\n");
            writer.write("\n");
            writer.write("IMPORTANT NOTES:\n");
            writer.write("---------------\n");
            writer.write("- This file is automatically generated and updated by the application.\n");
            writer.write("- Manual edits are supported but will be overwritten on next update.\n");
            writer.write("- Accounts are loaded from this file on application startup.\n");
            writer.write("- Changes made through the application UI will update this file.\n");
            writer.write("- The file serves as a backup when SQL database is unavailable.\n");
            writer.write("\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("\n");
            
            // Column headers
            writer.write("ACCOUNT DATA:\n");
            writer.write("------------\n");
            writer.write(String.format("%-15s | %-20s | %-20s | %-30s | %-20s | %-20s\n", 
                "ROLE", "USERNAME", "PASSWORD", "EMAIL", "CREATED DATE", "ORIGINAL USERNAME"));
            writer.write("────────────────────────────────────────────────────────────────────────────────\n");
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            
            // Write each user account
            if (users.isEmpty()) {
                writer.write("\nNo accounts found in database.\n");
            } else {
                for (UserData user : users) {
                    String createdDate = user.createdDate != null 
                        ? user.createdDate.toLocalDateTime().format(formatter)
                        : "N/A";
                    String role = user.role != null ? user.role : "Customer";
                    String username = user.username != null ? user.username : "";
                    String password = user.password != null ? user.password : "";
                    String email = user.email != null ? user.email : "";
                    String originalUsername = user.originalUsername != null ? user.originalUsername : "";
                    
                    writer.write(String.format("%-15s | %-20s | %-20s | %-30s | %-20s | %-20s\n",
                        role, username, password, email, createdDate, originalUsername
                    ));
                }
            }
            
            // Footer
            writer.write("────────────────────────────────────────────────────────────────────────────────\n");
            writer.write("\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("FILE STATISTICS:\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("Total Accounts: " + users.size() + "\n");
            writer.write("Last Updated: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + "\n");
            writer.write("\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("AUTOMATIC UPDATES:\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            writer.write("This file is automatically updated when:\n");
            writer.write("  - A new account is created (signup)\n");
            writer.write("  - An account profile is modified\n");
            writer.write("  - An account is deleted\n");
            writer.write("  - The application starts (loads existing accounts)\n");
            writer.write("\n");
            writer.write("The file maintains synchronization between SQL database and ArrayList storage.\n");
            writer.write("All account operations are reflected in this file immediately.\n");
            writer.write("═══════════════════════════════════════════════════════════════════════════════\n");
            
        } catch (IOException ex) {
            System.err.println("Error writing to notepad file: " + ex.getMessage());
        }
    }
}

